{% set name = "PyEVTK" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/paulo-herrera/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: cab240a2ea60b538395e440efe6ff1da9c7147b3110f5963eb5779fc867da675
  patches:
  - fix_manifest.patch

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python
    - pip
    - numpy >=1.8.0
    - pytest-runner

  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - evtk
    - evtk.hl
    - evtk.evtk
    - evtk.vtk
    - evtk.xml
  commands:
    - python -m evtk.examples.group
    - python -m evtk.examples.image
    - python -m evtk.examples.lines
    - python -m evtk.examples.lowlevel
    - python -m evtk.examples.points
    - python -m evtk.examples.poly_lines
    - python -m evtk.examples.rectilinear
    - python -m evtk.examples.structured
    - python -m evtk.examples.unstructured

about:
  home: https://github.com/paulo-herrera/PyEVTK
  license: BSD 2-clause
  license_family: BSD
  license_file: src/LICENSE
  summary: Export data as binary VTK files
  description: |
    EVTK (Export VTK) package allows exporting data to binary VTK files for
    visualization and data analysis with any of the visualization packages that
    support VTK files, e.g. Paraview, VisIt and Mayavi.
  dev_url: https://github.com/paulo-herrera/PyEVTK

extra:
  recipe-maintainers:
    - renefritze
    - xylar
