schema_version: 1

context:
  name: pyevtk
  version: "1.7.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 21ad3b1905b06bf288166629f0002d13a9c664eb42bcbed624d2032d7b8bcf52

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - numpy
    - setuptools
    - versioneer
    - pytest-runner
  run:
    - python >=${{ python_min }}
    - numpy

tests:
  - files:
      source:
        - examples/*.py
        - tests/*.py
    requirements:
      run:
        - pytest
        - python ${{ python_min }}.*
    script:
      - pytest tests/dummy.py

about:
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: |
    EVTK (Export VTK) package allows exporting data to binary VTK files for
    visualization and data analysis with any of the visualization packages that
    support VTK files, e.g. Paraview, VisIt and Mayavi. EVTK does not depend on
    any external library (e.g. VTK), so it is easy to install in different
    systems.
  homepage: https://github.com/pyscience-projects/pyevtk
  repository: https://github.com/paulo-herrera/PyEVTK

extra:
  recipe-maintainers:
    - xylar
    - MuellerSeb
